### ISSUE TITLE
Data outdated

### ISSUE THREAD

**Issue by joelcollinsdc** [datasets/airport-codes#2]
How is this data updated?  The source site has many additions that this data set does not contain...

I did some work in a fork to update the data, but I'm not sure if there is another process for maintaining...

https://github.com/joelcollinsdc/airport-codes/commit/f5908a6fc0d50ec790ab8f61a4998205802cf7ac

**Comment by sanh2o** [comment]
I added the data long time back for the first time, i am not sure who is maintaining it, feel free to contact the relevant person and update it.

**Comment by rgrp** [comment]
@joelcollinsdc we'd love to have a maintainer if you were interested and happy to have pull requests.

**Comment by AcckiyGerman** [comment]
FIXED:
The original source is that file http://ourairports.com/data/airports.csv 
This file containing information on all airports on the http://ourairports.com site and updates nightly.
The datahub.io will load, parse and transform this original source to the data-package here: http://datahub.io/core/airport-codes on daily basis.

This github data-package structure was taken as an example, and all the data wranglings are the same:
* coordinates field is added
* This fields are deleted:
            - id
            - longitude_deg
            - latitude_deg
            - scheduled_service
            - home_link
            - wikipedia_link
            - keywords

**Comment by rufuspollock** [comment]
@AcckiyGerman great and while you are at this can you update the github repo descriptions to have the correct links to the datahub.io page i.e. https://datahub.io/core/airport-codes in this case.

**Comment by AcckiyGerman** [comment]
The link was there already, but there were no highlighting that it is automated and nothing about datahub, so I added  `## Automation` title with this info.

**Comment by rufuspollock** [comment]
@AcckiyGerman this is not fixed. The link at the top of the github page points to data.okfn.org ... Please can you fix this ...

**Comment by AcckiyGerman** [comment]
@rufuspollock I cannot change the description on the github, as I'm not the owner (there is no edit button):
![image](https://user-images.githubusercontent.com/11707682/35907820-ac8cf84a-0bf7-11e8-975b-771985550481.png)

@sanh2o could you please update the airport-codes repository description (on top of the page) with the link to the datahub: http://datahub.io/core/airport-codes   ?

**Comment by zelima** [comment]
FIXED
